### ISSUE TITLE
Why not a package??

### ISSUE THREAD

**Issue by JemCdo** [LogicSatinn/custom-filament-login-page#1]

**Comment by LogicSatinn** [comment]
If there is time, I might look into that.

**Comment by LogicSatinn** [comment]
After giving this a thought, I don't think it's a good idea to make a package out of this idea. This repo is to stand as an example if somebody wishes to create a unique login page that doesn't look like the one provided by Filament.

**Comment by JemCdo** [comment]
@LogicSatinn does it mean I have to spun your entire laravel app to witness the magic, further more what if i want to use on my app??

**Comment by LogicSatinn** [comment]
The good ol' Copy and Paste @JemCdo
